version: '3.1'

services:

  nodejs-appl:
    image: pavanraj29/nodejs-app:72
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - 5000
    environment:
      - SERVICE_PORTS=5000
    networks:
      - web


  proxy:
    image: dockercloud/haproxy
    depends_on:
      - nodejs-appl
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay
